### ISSUE TITLE
Allow automaticaly tracking the newly created remote branch

### ISSUE THREAD

**Issue by rgarrigue** [Mergifyio/git-pull-request#112]
Hi there

I'm usually doing this : I create a new local branch, make some changes, commit, then `git pull-request`. Afterward, I always end up doing a `git push --set-upstream origin <remote_branch_created_by_pr> ` to push some fixes as suggested by the reviewer. If I `git pull-request` again, that overwrite changes made by other peoples.

Can you make it so "if not tracking a branch, track the newly created one" ? 

Thanks !

**Comment by jd** [comment]
what is "changes made by other people"? Not sure I follow. If they pushed to your branch, you have to `fetch` it before re-pushing, no?

**Comment by rgarrigue** [comment]
They push some minor changes like typo fixes in the doc. So yes I've to fetch anyway, but I'ld rather stop using git-pull-request force push once the pr is created. 

So I'ld like it to create the pr, track the PR's remote branch so I can be back on a "vanilla" workflow, working with a regular push
