### ISSUE TITLE
Allow to preserve older revision when push -f

### ISSUE THREAD

**Issue by jd** [Mergifyio/git-pull-request#15]
When doing `git push -f` to update the branch, the old version of the branch is unreachable because garbage collected by GitHub.

One solution to that would be to generate a random tag (e.g. uuid with a prefix based on the branch name and/or PR number) and use it to save the branch from being collected by GitHub.

See https://github.com/isaacs/github/issues/997 for context too.

**Comment by aspiers** [comment]
Very cool idea, thanks a lot! :smile:
