### ISSUE TITLE
Add config file support

### ISSUE THREAD

**Issue by vr** [Mergifyio/git-pull-request#24]
to set default value for --no-comment-on-update or --force-editor for example

**Comment by LiviuLvu** [comment]
Could not find a way to fix this issue:
$EDITOR is unset, you will not be able to edit the pull-request message

Tried to add a line in the .netrc file:
editor nano

But then the error turned to:
bad follower token '$EDITOR' (/Users/username/.netrc, line 2)

How to set up editor for --force-editor option?

Thanks!

**Comment by jd** [comment]
@LiviuLvu  you want `export EDITOR=nano` in your shell.

**Comment by LiviuLvu** [comment]
@jd  Thanks, that worked!
For reference, I added this line inside this file (mac OS):
~/.bash_profile

**Comment by jd** [comment]
This is now possible via `git config`.
