### ISSUE TITLE
making git-pull-request compatible with gitlab

### ISSUE THREAD

**Issue by 4383** [Mergifyio/git-pull-request#27]
Hey!

git-pull-request deal with `git` commands and github API, I thinks it's can be easy to made this project compatible with gitlab.

We just need to use the right API (github/gitlab) according to `git remote` url by example.

What do you think about this?

**Comment by jd** [comment]
I know nothing about Gitlab, but if it has the same idea of PR, why not!

**Comment by 4383** [comment]
The logical is the same... I use a on premise version of gitlab everyday and just the API calls changes.
In gitlab a `pull request` is called a `merge request` but the workflow is identical.

I can setup an testing environment on gitlab.com for implement this.

**Comment by 4383** [comment]
work in progress

**Comment by Thunder242** [comment]
#22

**Comment by danielmellado** [comment]
@4383 I assume that this got stalled? I was just searching for 'gitlab' with the same usecase xD

**Comment by 4383** [comment]
@danielmellado yeah this topic is totally outdated and can be abandoned.
