### ISSUE TITLE
Interactivity by default

### ISSUE THREAD

**Issue by bemoody** [Mergifyio/git-pull-request#31]
This is a great tool - thank you for creating it!

As with standard git commands (especially complicated and potentially destructive ones), it would be best for this tool to be "interactive by default", so that the user can see, in detail, what is going to be done, and confirm that it's what they want.

In particular, I think it's important not to create a forked repository, or publish any local commits, until after the user has confirmed their intentions.

(It also seems impolite to put words in the user's mouth - i.e., create a title/description automatically without giving the user a chance to edit it.)

So I would create a text file, like so:

    Pull request for mysweetbranch
    
    Add libfnord support.
    Use libfnord to frob the widgets.
    Highlight widgets that are not yet frobbed.
    
    # Creating a pull request from 'mysweetbranch' (3 commits)
    #     https://github.com/loser/asdf.git (new repository)
    # into 'origin/master'
    #     https://github.com/guru/asdf.git
    #
    # Enter a description for the pull request above.  Lines starting
    # with '#' will be ignored, and an empty message aborts the pull
    # request.

(or whatever; feel free to nitpick the exact phrasing)

then, invoke $EDITOR to edit this file, and if the result is empty or the editor aborts, then cancel the operation.

Once the user knows what they're doing, give them the option to make everything automatic.

**Comment by jd** [comment]
> In particular, I think it's important not to create a forked repository, or publish any local commits, until after the user has confirmed their intentions.

Yeah I guess the first run could ask to validate the creation of the fork.

> then, invoke $EDITOR to edit this file, and if the result is empty or the editor aborts, then cancel the operation.

Yeah, currently it's a bit too automatic I guess.

**Comment by jd** [comment]
This is now fixed.
