### ISSUE TITLE
In Windows git pull-request is not picking _netrc file

### ISSUE THREAD

**Issue by sarithaN** [Mergifyio/git-pull-request#54]
I am trying automate pull request and trying to setup in windows.
I have installed python , pip install httpie and  pip3 install git-pull-request
and I have created _netrc file for credentials  under user profile, but when I am trying to run git pull-request after commit, I am getting this error.
Unable to find your GitHub credentials for xyz@bitbucket.org.
Make sure you have a line like this in your ~/.netrc file:
machine xyz@bitbucket.org login <login> password <pwd>, or use git store credentials

Please can any one help me in solving this.

**Comment by jd** [comment]
You really need a file named `.netrc` I guess, not `_netrc`. We should probaly use `git credential` to get the config at this point.

**Comment by sarithaN** [comment]
For windows _netrc has to be used instead of .netrc.
I am using git credentials also
When I check the vi ~/.git-credentials
the file has two entries of my username and password.

https://usr:pwd@bitbucket.org/
https://usr:pwd@bitbucket.org/

I am able to do push without any errors
If I do git pull-request then I am seeing errors. Is anything has to be added for pull-request cmd?

**Comment by jd** [comment]
That's good to know. Though I'm concerned you're talking about BitBucket since this tool only support GitHub and Pagure.

**Comment by jd** [comment]
We now use git credential.
