### ISSUE TITLE
Add Gitlab support

### ISSUE THREAD

**Issue by ShalokShalom** [Mergifyio/git-pull-request#64]
Hi there. I git clone something, change the files, git add . then git commit the whole thing. 

git pull-request then asks me for my credentials for that repo. 

What is the sense of a program like this, when it assumes that I have commit privileges for the named repo?

**Comment by ShalokShalom** [comment]
Sorry, forget what I said.  You dont support Gitlab.

**Comment by jd** [comment]
See #27
