### ISSUE TITLE
Can't create a PR if 2FA is enabled

### ISSUE THREAD

**Issue by miguelriosoliveira** [Mergifyio/git-pull-request#92]
The tool cannot login in the user account if the user has enabled the Two Factor Authentication.

**Comment by jd** [comment]
It can, I'm using it with 2FA accounts. Can you provide more details?

**Comment by miguelriosoliveira** [comment]
This is what happened when I tried:
![image](https://user-images.githubusercontent.com/12296400/69723809-480e0180-10f9-11ea-9c6a-e8e777c2e36b.png)

**Comment by jd** [comment]
As the message says, you need to provide an OTP code, not your regular password.

https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line

**Comment by miguelriosoliveira** [comment]
I think a get it. Thanks for the help!
